#!/usr/bin/env bash
#
# update-homebrew-tap.sh — regenerate one formula in facetlayer/homebrew-tap
# from the release assets of a tag in this repo, then commit and push it.
#
# This repo publishes more than one Homebrew package (garden today, the `petal`
# CLI later), so the formula-writing logic lives here rather than inline in a
# single release workflow. Each package's release workflow checks the tap out at
# ./tap, sets the variables below, and calls this script.
#
# Required environment:
#   FORMULA      formula/binary name, e.g. "garden"        -> tap/Formula/garden.rb
#   CLASS        Ruby class name, e.g. "Garden"            (Homebrew derives this
#                from the file name, so it must match FORMULA)
#   DESC         one-line `desc` string
#   HOMEPAGE     `homepage` URL
#   VERSION      version without the leading v, e.g. "0.2.0"
#   TAG          the git tag the assets hang off, e.g. "garden-v0.2.0"
#   REPO         owner/name the release lives in, e.g. "andyfischer/petal"
#   ASSET_PREFIX basename of the tarballs, e.g. "garden" for garden-<target>.tar.gz
#   BINS         space-separated binaries inside the tarball to install
#   TEST_CMD     Ruby body for the formula's `test do` block
# Optional:
#   CAVEATS      Ruby body for a `caveats` block; omitted when empty
#   TAP_DIR      tap checkout (default: tap)
#
# A target is included only when its checksum is present in SHA256SUMS, so a
# macOS-only package emits a macOS-only formula and a package that also ships
# Linux builds picks those up with no change here.

set -euo pipefail

: "${FORMULA:?}" "${CLASS:?}" "${DESC:?}" "${HOMEPAGE:?}" "${VERSION:?}"
: "${TAG:?}" "${REPO:?}" "${ASSET_PREFIX:?}" "${BINS:?}" "${TEST_CMD:?}"
TAP_DIR="${TAP_DIR:-tap}"
CAVEATS="${CAVEATS:-}"

# sha_for <rust-target> — the checksum for that target's tarball, or empty if
# this release has no build for it.
sha_for() {
    awk -v want="${ASSET_PREFIX}-$1.tar.gz" '$2 == want || $2 == "*" want { print $1 }' SHA256SUMS
}

url_for() {
    echo "https://github.com/${REPO}/releases/download/${TAG}/${ASSET_PREFIX}-$1.tar.gz"
}

# emit_arch <on_arm|on_intel> <target> — one arch block, or nothing when this
# release has no build for that target. Note that every `$(...)` below strips
# trailing newlines, so each printf re-adds the ones it needs.
emit_arch() {
    local kind="$1" target="$2" sha
    sha="$(sha_for "$target")"
    [ -n "$sha" ] || return 0
    printf '    %s do\n' "$kind"
    printf '      url "%s"\n' "$(url_for "$target")"
    printf '      sha256 "%s"\n' "$sha"
    printf '    end\n'
}

# on_arm/on_intel only make sense inside an on_macos/on_linux that has at least
# one build; emit the whole os block only when it is non-empty.
emit_os() {
    local os="$1" arm_target="$2" intel_target="$3" body
    body="$(emit_arch on_arm "$arm_target"; emit_arch on_intel "$intel_target")"
    [ -n "$body" ] || return 0
    printf '  on_%s do\n%s\n  end\n\n' "$os" "$body"
}

bottles="$(
    emit_os macos aarch64-apple-darwin x86_64-apple-darwin
    emit_os linux aarch64-unknown-linux-gnu x86_64-unknown-linux-gnu
)"
if [ -z "$bottles" ]; then
    echo "no release assets matched ${ASSET_PREFIX}-<target>.tar.gz in SHA256SUMS" >&2
    cat SHA256SUMS >&2
    exit 1
fi

# `bin.install` takes the binaries as a Ruby argument list.
install_args=""
for b in $BINS; do
    install_args="${install_args:+$install_args, }\"$b\""
done

mkdir -p "$TAP_DIR/Formula"
{
    echo "# Generated by ${REPO} .github/workflows — do not edit by hand."
    echo "class ${CLASS} < Formula"
    echo "  desc \"${DESC}\""
    echo "  homepage \"${HOMEPAGE}\""
    echo "  version \"${VERSION}\""
    echo "  license \"MIT\""
    echo
    printf '%s\n\n' "$bottles"
    echo "  def install"
    echo "    bin.install ${install_args}"
    echo "  end"
    if [ -n "$CAVEATS" ]; then
        echo
        echo "  def caveats"
        echo "    <<~EOS"
        printf '%s\n' "$CAVEATS" | sed 's/^/      /'
        echo "    EOS"
        echo "  end"
    fi
    echo
    echo "  test do"
    printf '%s\n' "$TEST_CMD" | sed 's/^/    /'
    echo "  end"
    echo "end"
} > "$TAP_DIR/Formula/${FORMULA}.rb"

echo "==> wrote $TAP_DIR/Formula/${FORMULA}.rb"
cat "$TAP_DIR/Formula/${FORMULA}.rb"

cd "$TAP_DIR"
git config user.name "github-actions[bot]"
git config user.email "github-actions[bot]@users.noreply.github.com"
# Stage before diffing: on a package's first release the formula is untracked,
# and plain `git diff` does not report untracked files.
git add "Formula/${FORMULA}.rb"
if git diff --cached --quiet; then
    echo "formula unchanged"
    exit 0
fi
git commit -m "${FORMULA} ${VERSION}"
git push
