//! Copy propagation and dead-move elimination over lowered bytecode.
//!
//! Lowering gives every IR term its own flat register, and the term graph has a
//! `Copy` term for every *use* of a variable plus a `Phi` for every rebinding —
//! so the instruction stream that comes out is roughly half `Move`. On the
//! spreadsheet benchmark, 47% of all retired instructions were moves; each one
//! is a register read, a register write, and a full trip through the dispatch
//! loop, which is the most expensive part of executing a cheap instruction.
//!
//! This pass runs after lowering (and after `lastuse`, so it cannot disturb the
//! alias groups that route A reasons about) and does two standard things:
//!
//! 1. **Copy propagation.** A forward dataflow computes, at every program
//!    point, which registers are known to hold the same value as another
//!    (`d ≡ s`, generated by `Move d <- s`, killed when either side is
//!    rewritten). Reads of `d` are rewritten to read `s`. This alone removes no
//!    instructions — it makes the moves *dead*.
//! 2. **Dead-move elimination.** A backward liveness pass finds moves whose
//!    destination is not live afterwards. Those are dropped, the code is
//!    compacted, and every branch target is remapped.
//!
//! Self-moves (`Move d <- d`, which lowering emits at some join edges) are
//! dropped unconditionally — nothing can observe them.
//!
//! # What is deliberately preserved
//! A `Move` whose origin term is **named** is kept even when dead. Naming is
//! exactly the filter the VM's observation buffer applies (`Vm::is_observable`),
//! and an embedder reads a frame's bindings out of that buffer — Garden's
//! `panel.values` and the debug server's `/state` are this, and the `--observe`
//! CLI dump is too. Deleting the instruction that writes `d` would silently drop
//! the binding from that report. Unnamed temporaries have no such reader.
//!
//! The `explain` *trace* is thinned by this pass (a propagated-away move retires
//! no entry). That is the same best-effort contract in-place mutation and
//! register reuse already establish for it.
//!
//! # Soundness
//! Propagation only rewrites a read of `d` to `s` at a point where every path
//! reaching it passes a `Move d <- s` with no intervening write to either
//! register — the meet is intersection over predecessors, so a fact must hold on
//! *all* paths, and any write to either side kills it. A move is deleted only
//! when its destination is dead on every path out, which is a whole-function
//! backward analysis over the same CFG (`falls_through` + `branch_target`) the
//! last-use pass uses. Registers that a frame push fills in (parameters,
//! captures, the self-reference) have no defining instruction, and the
//! function's `result_reg` is treated as live at the exit, so neither can be
//! deleted out from under the frame protocol.

use std::collections::HashMap;

use super::isa::{BytecodeFn, BytecodeProgram, Inst, Reg};
use crate::program::{Program, TermId};

/// What one run of the pass changed, for tests and for the `PETAL_OPT_STATS`
/// dump.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
pub struct CopyPropStats {
    /// Operand reads rewritten to a propagated source register.
    pub rewritten: usize,
    /// `Move` instructions deleted.
    pub removed: usize,
    /// Branches retargeted past an intervening `Jump`, plus `Jump`s to the very
    /// next instruction that were dropped.
    pub threaded: usize,
    /// Instructions in the program before the pass.
    pub before: usize,
    /// Instructions in the program after it.
    pub after: usize,
}

/// Run the pass over every function of `bc`.
///
/// `preserve_observations` keeps every dead-but-named `Move`, so a host reading
/// a run's bindings back (`--observe`, Garden's `panel.values`) sees the same
/// set it would without the pass. It costs real instructions — the named moves
/// are the phi copies of user variables, the most frequent kind — so it is set
/// only when something is actually observing. See [`crate::backend::OptFlags`].
pub fn apply(
    bc: &mut BytecodeProgram,
    program: &Program,
    preserve_observations: bool,
) -> CopyPropStats {
    let mut stats = CopyPropStats::default();
    let match_binds = std::mem::take(&mut bc.match_binds);
    apply_fn(
        &mut bc.root,
        program,
        &match_binds,
        preserve_observations,
        &mut stats,
    );
    for f in &mut bc.fns {
        apply_fn(f, program, &match_binds, preserve_observations, &mut stats);
    }
    bc.match_binds = match_binds;
    stats
}

type Binds = HashMap<(TermId, u16), Vec<(String, Reg)>>;

/// How many propagate/eliminate rounds to run per function. Deleting a copy can
/// expose the one that fed it, so a second pass finds more than the first; the
/// third rarely finds anything, which is where the loop stops.
const PASSES: usize = 3;

fn apply_fn(
    f: &mut BytecodeFn,
    program: &Program,
    binds: &Binds,
    preserve_observations: bool,
    stats: &mut CopyPropStats,
) {
    stats.before += f.code.len();
    for _ in 0..PASSES {
        if f.code.is_empty() {
            break;
        }
        stats.rewritten += propagate(f, binds);
        let removed = eliminate(f, program, binds, preserve_observations);
        stats.removed += removed;
        if removed == 0 {
            break;
        }
    }
    stats.threaded += thread_jumps(f);
    stats.after += f.code.len();
}

// ---------------------------------------------------------------------------
// CFG
// ---------------------------------------------------------------------------

/// Successor instruction indices of `j`. `code.len()` is the exit pseudo-node
/// (running off the end of the function), which is also where an out-of-range
/// branch target lands.
fn succs(code: &[Inst], j: usize) -> Vec<usize> {
    let exit = code.len();
    let mut out = Vec::with_capacity(2);
    if code[j].falls_through() {
        out.push((j + 1).min(exit));
    }
    if let Some(to) = code[j].branch_target() {
        out.push((to as usize).min(exit));
    }
    out
}

/// Predecessor lists, indexed by instruction (entry `code.len()` is the exit
/// node and is not itself a predecessor of anything).
fn preds(code: &[Inst]) -> Vec<Vec<usize>> {
    let mut p = vec![Vec::new(); code.len() + 1];
    for j in 0..code.len() {
        for s in succs(code, j) {
            p[s].push(j);
        }
    }
    p
}

// ---------------------------------------------------------------------------
// 1. Copy propagation
// ---------------------------------------------------------------------------

/// The copy facts holding at a program point: `map[d] == Some(s)` means "`d`
/// currently holds the same value as `s`". `None` for the not-yet-computed
/// (bottom) state of an unreached point.
type Facts = HashMap<Reg, Reg>;

/// Rewrite operand reads to their propagated sources. Returns how many reads
/// were rewritten.
fn propagate(f: &mut BytecodeFn, binds: &Binds) -> usize {
    let n = f.code.len();
    let preds = preds(&f.code);
    // `in_facts[j]` is the meet of every predecessor's out-facts.
    let mut in_facts: Vec<Option<Facts>> = vec![None; n];
    in_facts[0] = Some(Facts::new());

    // Forward fixpoint. Bounded: facts only ever shrink after the first visit
    // (meet is intersection), so a worklist over instructions converges in a
    // few passes for the shapes lowering produces.
    let mut changed = true;
    let mut rounds = 0;
    while changed && rounds < MAX_ROUNDS {
        changed = false;
        rounds += 1;
        for j in 0..n {
            let entry = match meet(&preds[j], &in_facts, &f.code, binds, j == 0) {
                Some(e) => e,
                None => continue, // unreachable so far
            };
            if in_facts[j].as_ref() != Some(&entry) {
                in_facts[j] = Some(entry);
                changed = true;
            }
        }
    }

    let mut rewritten = 0;
    for j in 0..n {
        let Some(facts) = &in_facts[j] else { continue };
        if facts.is_empty() {
            continue;
        }
        // Every read — including a `Move`'s own source — follows the fact chain
        // to its root, so a chain of copies collapses to reads of one register
        // in a single pass and the intermediate links fall out as dead.
        f.code[j].for_each_read_mut(|r| {
            if let Some(root) = resolve(facts, *r) {
                if root != *r {
                    *r = root;
                    rewritten += 1;
                }
            }
        });
    }
    rewritten
}

/// Cap on dataflow iterations. Each round is O(instructions); the bound exists
/// so a pathological CFG degrades to "optimize less" rather than to a hang.
const MAX_ROUNDS: usize = 16;

/// Follow `d ≡ s` links to the end of the chain. Cycles cannot arise (a fact is
/// killed when its destination is rewritten) but the hop budget makes that
/// structural rather than assumed.
fn resolve(facts: &Facts, mut r: Reg) -> Option<Reg> {
    let mut out = None;
    for _ in 0..8 {
        match facts.get(&r) {
            Some(&s) if s != r => {
                r = s;
                out = Some(s);
            }
            _ => break,
        }
    }
    out
}

/// Facts entering instruction `j`: the intersection of every predecessor's
/// out-facts, or an empty set for the function entry.
fn meet(
    preds: &[usize],
    in_facts: &[Option<Facts>],
    code: &[Inst],
    binds: &Binds,
    is_entry: bool,
) -> Option<Facts> {
    let mut acc: Option<Facts> = if is_entry { Some(Facts::new()) } else { None };
    for &p in preds {
        let Some(pin) = &in_facts[p] else { continue };
        let out = transfer(pin, &code[p], binds);
        acc = Some(match acc {
            None => out,
            Some(a) => a
                .into_iter()
                .filter(|(d, s)| out.get(d) == Some(s))
                .collect(),
        });
    }
    acc
}

/// Facts leaving instruction `i`, given the facts entering it: kill anything
/// mentioning a register `i` writes, then generate the copy `i` establishes.
fn transfer(facts: &Facts, inst: &Inst, binds: &Binds) -> Facts {
    let mut out = facts.clone();
    inst.for_each_write(binds, |w| {
        out.remove(&w);
        out.retain(|_, s| *s != w);
    });
    if let Inst::Move { dst, src } = inst {
        if dst != src {
            out.insert(*dst, *src);
        }
    }
    out
}

// ---------------------------------------------------------------------------
// 2. Dead-move elimination
// ---------------------------------------------------------------------------

/// Delete moves whose destination is dead afterwards (plus every self-move),
/// compact the code, and remap branch targets. Returns how many were deleted.
fn eliminate(
    f: &mut BytecodeFn,
    program: &Program,
    binds: &Binds,
    preserve_observations: bool,
) -> usize {
    let n = f.code.len();
    let live_out = liveness(f, binds);

    let mut drop_it = vec![false; n];
    let mut removed = 0;
    for j in 0..n {
        // A self-move is unobservable even when its origin term is named: the
        // register already holds the value an observation would record, and the
        // VM reads `dst` *after* the instruction to record it.
        if let Inst::Move { dst, src } = f.code[j] {
            if dst == src {
                drop_it[j] = true;
                removed += 1;
                continue;
            }
        }
        if !is_pure(&f.code[j]) {
            continue;
        }
        let Some(dst) = f.code[j].dst() else { continue };
        if live_out[j].contains(&dst) {
            continue;
        }
        if preserve_observations && is_observable(program, f.origins.get(j).copied().flatten()) {
            continue;
        }
        drop_it[j] = true;
        removed += 1;
    }
    if removed > 0 {
        compact(f, &drop_it);
    }
    removed
}

/// Whether an instruction can be dropped when its destination is dead: it must
/// compute its result without doing anything else observable. Arithmetic is
/// deliberately excluded — division raises on a zero divisor, and a dropped
/// `Div` would turn a program that errors into one that does not.
fn is_pure(inst: &Inst) -> bool {
    matches!(
        inst,
        Inst::Move { .. } | Inst::LoadConst { .. } | Inst::LoadNil { .. } | Inst::LoadBool { .. }
    )
}

/// Whether an instruction's origin term is one the observation buffer would
/// record — the same test the VM applies in `Vm::is_observable`. Kept in sync
/// with it by construction: both ask for a name and reject builtin phantoms.
fn is_observable(program: &Program, origin: Option<TermId>) -> bool {
    let Some(tid) = origin else { return false };
    let term = program.get_term(tid);
    term.name.is_some() && !crate::ir_display::is_phantom(program, term)
}

/// Registers live *after* each instruction. Backward fixpoint over the CFG:
/// `live_out[j] = ⋃ live_in[s]` over successors, `live_in[j] = reads(j) ∪
/// (live_out[j] \ writes(j))`. The exit node starts with the function's result
/// register live, since a frame that runs off the end delivers it.
fn liveness(f: &BytecodeFn, binds: &Binds) -> Vec<Vec<Reg>> {
    let n = f.code.len();
    let mut live_in: Vec<Vec<Reg>> = vec![Vec::new(); n + 1];
    if let Some(r) = f.result_reg {
        live_in[n].push(r);
    }
    let mut changed = true;
    let mut rounds = 0;
    while changed && rounds < MAX_ROUNDS * 4 {
        changed = false;
        rounds += 1;
        for j in (0..n).rev() {
            let mut out: Vec<Reg> = Vec::new();
            for s in succs(&f.code, j) {
                for &r in &live_in[s] {
                    if !out.contains(&r) {
                        out.push(r);
                    }
                }
            }
            let mut new_in = out;
            f.code[j].for_each_write(binds, |w| new_in.retain(|&r| r != w));
            for r in f.code[j].read_regs() {
                if !new_in.contains(&r) {
                    new_in.push(r);
                }
            }
            new_in.sort_unstable();
            if new_in != live_in[j] {
                live_in[j] = new_in;
                changed = true;
            }
        }
    }
    // Re-derive live-out from the converged live-in sets.
    (0..n)
        .map(|j| {
            let mut out: Vec<Reg> = Vec::new();
            for s in succs(&f.code, j) {
                for &r in &live_in[s] {
                    if !out.contains(&r) {
                        out.push(r);
                    }
                }
            }
            out
        })
        .collect()
}

/// Drop the marked instructions and renumber every branch target. A target that
/// pointed at a dropped instruction moves to the next surviving one (dropping
/// only ever removes a `Move`, so "the next instruction" is where control was
/// going anyway).
fn compact(f: &mut BytecodeFn, drop_it: &[bool]) {
    let n = f.code.len();
    // new_index[j] = where instruction j landed; for a dropped j, where control
    // arriving at j now lands. `new_index[n]` is the new end-of-code.
    let mut new_index = vec![0u32; n + 1];
    let mut next = 0u32;
    for j in 0..n {
        new_index[j] = next;
        if !drop_it[j] {
            next += 1;
        }
    }
    new_index[n] = next;

    let mut code = Vec::with_capacity(next as usize);
    let mut origins = Vec::with_capacity(next as usize);
    for j in 0..n {
        if drop_it[j] {
            continue;
        }
        let mut inst = f.code[j].clone();
        if let Some(t) = inst.branch_target_mut() {
            let old = (*t as usize).min(n);
            *t = new_index[old];
        }
        code.push(inst);
        origins.push(f.origins.get(j).copied().flatten());
    }
    f.code = code;
    f.origins = origins;
}

/// Jump threading: retarget every branch that lands on an unconditional `Jump`
/// to that jump's own destination, then drop any `Jump` left pointing at the
/// instruction after it. Lowering produces both shapes routinely — an `if` arm
/// jumps to the join, which is itself the loop's back-edge jump — and each one
/// costs a full dispatch to accomplish nothing.
fn thread_jumps(f: &mut BytecodeFn) -> usize {
    let n = f.code.len();
    // Resolve each label to its final destination first, so the rewrite below
    // is a lookup rather than a walk (and so a `Jump` cycle, which unreachable
    // code can produce, terminates).
    let mut dest: Vec<u32> = (0..=n as u32).collect();
    for j in 0..n {
        let mut t = j;
        for _ in 0..n.min(64) {
            match f.code.get(t) {
                Some(Inst::Jump { to }) if (*to as usize) != t => t = *to as usize,
                _ => break,
            }
        }
        dest[j] = t.min(n) as u32;
    }

    let mut threaded = 0;
    for j in 0..n {
        if let Some(t) = f.code[j].branch_target_mut() {
            let resolved = dest[(*t as usize).min(n)];
            if resolved != *t {
                *t = resolved;
                threaded += 1;
            }
        }
    }

    let mut drop_it = vec![false; n];
    for j in 0..n {
        if let Inst::Jump { to } = f.code[j] {
            if to as usize == j + 1 {
                drop_it[j] = true;
                threaded += 1;
            }
        }
    }
    if drop_it.iter().any(|d| *d) {
        compact(f, &drop_it);
    }
    threaded
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::backend::bytecode::isa::Opcode;
    use crate::env::Env;

    /// Compile `src`, then lower it twice — without the pass and with it. The
    /// `Env` is returned alongside because it owns the `Program` the lowerings
    /// (and the origin-term assertions) borrow.
    fn lowered(src: &str) -> (BytecodeProgram, BytecodeProgram, Env) {
        let mut env = Env::new();
        let pid = env.load_program(src).expect("compiles");
        let program = env.get_program(pid).expect("program");
        let plain = super::super::lower_program(program).expect("lowers");
        let mut opt = super::super::lower_program(program).expect("lowers");
        apply(&mut opt, program, true);
        (plain, opt, env)
    }

    fn count(bc: &BytecodeProgram, op: Opcode) -> usize {
        std::iter::once(&bc.root)
            .chain(bc.fns.iter())
            .flat_map(|f| f.code.iter())
            .filter(|i| i.opcode() == op)
            .count()
    }

    /// Run `src` with the pass off and on, assert the two agree, and return the
    /// output. Equality with the unoptimized lowering is the property that
    /// matters — an absolute expectation would only restate the language's
    /// semantics, which are tested elsewhere.
    fn run_both(src: &str) -> String {
        let go = |flags: crate::backend::OptFlags| {
            let mut env = Env::new();
            env.set_opt_flags(flags);
            let pid = env.load_program(src).expect("loads");
            let sid = env.create_stack(pid).expect("stack");
            let value = env.run(sid).expect("runs");
            let rendered = crate::value::value_to_display_string(&value, env.heap());
            (rendered, env.take_output().join("\n"))
        };
        let plain = go(crate::backend::OptFlags::none());
        let opt = go(crate::backend::OptFlags::all());
        assert_eq!(
            plain, opt,
            "copy propagation changed the program's behavior"
        );
        opt.1
    }

    #[test]
    fn removes_moves_from_a_hot_loop() {
        let (plain, opt, _) = lowered(
            "fn digit(c)\n  let d = -1\n  for i in range(0, 10) do\n    if i == c then d = i end\n  end\n  d\nend\nprint(digit(7))",
        );
        let before = count(&plain, Opcode::Move);
        let after = count(&opt, Opcode::Move);
        assert!(
            after < before,
            "expected fewer moves after the pass, got {before} -> {after}"
        );
    }

    #[test]
    fn keeps_a_named_move_that_an_observer_would_read() {
        // `total` is a named term: its carry-out move must survive even though
        // nothing reads the register afterwards, or `--observe` loses it.
        let src = "let total = 0\nfor i in range(0, 3) do\n  total = total + i\nend\nprint(total)";
        let (_, opt, env) = lowered(src);
        let program = env
            .get_program(crate::program::ProgramId(1))
            .expect("program");
        let kept = std::iter::once(&opt.root)
            .chain(opt.fns.iter())
            .flat_map(|f| f.code.iter().zip(f.origins.iter()))
            .any(|(i, o)| {
                matches!(i, Inst::Move { .. })
                    && o.map(|t| program.get_term(t).name.as_deref() == Some("total"))
                        .unwrap_or(false)
            });
        assert!(kept, "the named `total` move was eliminated");
    }

    #[test]
    fn without_the_observation_guard_the_named_move_goes() {
        let src = "let total = 0\nfor i in range(0, 3) do\n  total = total + i\nend\nprint(total)";
        let mut env = Env::new();
        let pid = env.load_program(src).expect("compiles");
        let program = env.get_program(pid).expect("program");
        let mut kept = super::super::lower_program(program).expect("lowers");
        let mut freed = super::super::lower_program(program).expect("lowers");
        let with_guard = apply(&mut kept, program, true);
        let without = apply(&mut freed, program, false);
        assert!(
            without.removed > with_guard.removed,
            "the guard should be costing instructions ({} vs {})",
            with_guard.removed,
            without.removed
        );
    }

    #[test]
    fn self_moves_are_always_dropped() {
        let (plain, opt, _) = lowered(
            "fn f(c)\n  let d = 0\n  for i in range(0, 4) do\n    if i == c then d = i end\n  end\n  d\nend\nprint(f(2))",
        );
        let self_moves = |bc: &BytecodeProgram| {
            std::iter::once(&bc.root)
                .chain(bc.fns.iter())
                .flat_map(|f| f.code.iter())
                .filter(|i| matches!(i, Inst::Move { dst, src } if dst == src))
                .count()
        };
        assert!(self_moves(&plain) > 0, "fixture has no self-moves to drop");
        assert_eq!(self_moves(&opt), 0);
    }

    #[test]
    fn branch_targets_survive_compaction() {
        // Every jump must still land on the instruction it named, so the
        // program's *output* is the assertion that matters.
        let src = "let acc = 0\nfor i in range(0, 6) do\n  if i % 2 == 0 then\n    acc = acc + i\n  else\n    acc = acc - 1\n  end\nend\nprint(acc)";
        assert_eq!(run_both(src), "3");
    }

    #[test]
    fn nested_calls_and_closures_still_run() {
        let src = "fn adder(n)\n  let f = fn(x) -> x + n\n  f\nend\nlet add3 = adder(3)\nprint(add3(4))\nprint(map([1, 2, 3], fn(x) -> x * 2))";
        assert_eq!(run_both(src), "7\n[2, 4, 6]");
    }

    #[test]
    fn stats_account_for_every_instruction() {
        let mut env = Env::new();
        let pid = env
            .load_program("let a = 1\nlet b = a + 1\nprint(b)")
            .expect("compiles");
        let program = env.get_program(pid).expect("program");
        let mut bc = super::super::lower_program(program).expect("lowers");
        let stats = apply(&mut bc, program, true);
        assert_eq!(stats.before - stats.removed, stats.after);
    }
}
