#! /usr/bin/env tsx

import Path from 'path';
import Fs from 'fs/promises';
import { everyBytecodeOp } from './bytecodeOps';

const ProjectRootDir = Path.join(__dirname, '..');

async function write_bytecode_encoding_h() {
    const file_lines: string[] = [];
    file_lines.push("// This file was generated by ./ts/generateCpp.ts");
    file_lines.push("// Don't modify this file by hand.");
    file_lines.push("// To change any bytecode operations, update ./ts/bytecodeOps.ts and then run `yarn generate:cpp`");
    file_lines.push('');
    file_lines.push('#pragma once');
    file_lines.push('');
    file_lines.push('#include "standard_headers.h"');
    file_lines.push('#include "bytecode_helpers.h"');
    file_lines.push('#include "globals/global_state.h"');
    file_lines.push('#include <iostream>');
    file_lines.push('');
    file_lines.push('// Const values //');
    file_lines.push('');
    for (const { const_ident, value, comment } of everyBytecodeOp()) {
        if (comment) {
            file_lines.push(`// ${comment}`);
        }
        file_lines.push(`const u8 ${const_ident} = 0x${value.toString(16)};`);
    }
    file_lines.push("");
    file_lines.push('// pack functions //');
    file_lines.push('');
    for (const { const_ident, name, total_bit_size, params } of everyBytecodeOp()) {
        let function_params = (params || []).map(param => {
            const param_name = param.name.replace(/^\s+|\s+$/g, '');
            const param_type = param.type.replace(/^\s+|\s+$/g, '');
            return `${param_type} ${param_name}`;
        });
        file_lines.push(`Instruction pack_${name}(${function_params.join(', ')}) {`);
        file_lines.push(`    Instruction isn = ${const_ident} << 24;`);

        let next_bit_start = 8;
        for (const param of params || []) {
            let required_shift = 32 - next_bit_start - param.bit_size;
            if (required_shift < 0) {
                throw new Error(`Opcode params too big, required shift is negative: ${required_shift} for ${name} ${param.name}`);
            }
            switch (param.type) {
                case 'u8':
                    file_lines.push(`    isn |= ${param.name} << ${required_shift};`);
                    break;
                case 'u16':
                    file_lines.push(`    isn |= ${param.name} << ${required_shift};`);
                    break;
                case 'u32':
                    file_lines.push(`    isn |= ${param.name} << ${required_shift};`);
                    break;
                default:
                    file_lines.push(`    isn |= ${param.name} << ${required_shift};`);
                    break;
            }
            next_bit_start += param.bit_size;
        }

        file_lines.push(`    return isn;`);
        file_lines.push(`}`);
        file_lines.push('');
    }
    file_lines.push('');
    file_lines.push('// unpack functions //');
    file_lines.push('');
    for (const { name, params } of everyBytecodeOp()) {

        let next_bit_start = 8;
        for (const param of params) {
            let required_shift = 32 - next_bit_start - param.bit_size;

            file_lines.push(`${param.type} unpack_${name}__${param.name}(const Instruction ins) {`);

            //for (const param of params) {
            //    let line_parts = [`let ${param.name}: ${param.type} = `];
            switch (param.type) {
                case 'u8':
                    file_lines.push(`    return (ins >> ${required_shift}) & 0xFF;`);
                    break;
                case 'u16':
                    file_lines.push(`    return (ins >> ${required_shift}) & 0xFFFF;`);
                    break;
                case 'u32':
                    file_lines.push(`    return (ins >> ${required_shift}) & 0xFFFFFFFF;`);
                    break;
                case 'i16':
                    file_lines.push(`    return (ins >> ${required_shift}) & 0xFFFF;`);
                    break;
                case 'i32':
                    file_lines.push(`    return (ins >> ${required_shift}) & 0xFFFFFFFF;`);
                    break;
                case 'f32':
                    file_lines.push(`    return (ins >> ${required_shift}) & 0xFFFFFFFF;`);
                    break;
                default:
                    throw new Error(`Unhandled type: ${param.type}`);
            }
            file_lines.push('}');
            file_lines.push('');

            next_bit_start += param.bit_size;
        }
    }
    file_lines.push('// to_string functions //');
    file_lines.push('');
    file_lines.push(`const char* bytecode_opcode_to_string(u8 opcode) {`);
    file_lines.push(`    switch (opcode) {`);
    for (const { const_ident, name } of everyBytecodeOp()) {
        file_lines.push(`        case ${const_ident}: return "${name}";`);
    }
    file_lines.push(`        default: return "(unknown opcode)";`);
    file_lines.push(`    }`);
    file_lines.push(`}`);
    file_lines.push(``);
    file_lines.push(``);
    /*
    file_lines.push(`void bytecode_opcode_get_stack_effect(u8 opcode, i8* stac) -> (i8, i8) {`);
    file_lines.push(`    match opcode {`);
    for (const { const_ident, stack_pop, stack_push } of everyBytecodeOp()) {
        if (!stack_pop && !stack_push)
            continue;
        file_lines.push(`        ${const_ident} => (${stack_pop}, ${stack_push}),`);
    }
    file_lines.push(`        _ => (0, 0),`);
    file_lines.push(`    }`);
    file_lines.push(`}`);
    */

    file_lines.push(``);
    file_lines.push(`u32 bytecode_opcode_get_isn_size(u8 opcode) {`);
    file_lines.push(`    switch (opcode) {`);
    for (const { const_ident, total_bit_size } of everyBytecodeOp()) {
        file_lines.push(`        case ${const_ident}: return ${total_bit_size / 8};`);
    }
    file_lines.push(`        default: throw new std::runtime_error("Unknown opcode");`);
    file_lines.push(`    }`);
    file_lines.push(`}`);
    file_lines.push(``);

    /*
    file_lines.push(`pub fn builtin_func_to_opcode(func: NativeFunction) -> u8 {`);
    file_lines.push(`    match func {`);
    for (const { native_func_name, const_ident } of everyBytecodeOp()) {
        if (native_func_name) {
            file_lines.push(`        NativeFunction::${native_func_name} => ${const_ident},`);
        }
    }
    file_lines.push(`        _ => 0,`);
    file_lines.push(`    }`);
    file_lines.push(`}`);
    file_lines.push(``);
    */

    file_lines.push(`void debug_format_instruction(std::ostream& out, Instruction ins) {`);
    file_lines.push(`    u8 opcode = unpack_opcode(ins);`);
    file_lines.push(`    out << bytecode_opcode_to_string(opcode);`);
    file_lines.push(`    switch (opcode) {`);
    for (const { const_ident, name, params } of everyBytecodeOp()) {
        if (params.length === 0)
            continue;
        file_lines.push(`        case ${const_ident}: {`);
        for (const param of params) {
            file_lines.push(`            ${param.type} ${param.name} = unpack_${name}__${param.name}(ins);`);
        }
        let formatted_params = params.map(param => {
            if (param.name === 'error_code' && name === 'op_compile_error') {
                return `bytecode_compile_error_to_string(${param.name})`;
            }
            return param.name;
        });

        let rhs_parts: string[] = [];
        for (const param of params) {
            rhs_parts.push(` << " ${param.name}:"`);
            if (param.type === 'u8') {
                // add a cast to make sure that it's printed as an integer
                rhs_parts.push(` << (u32)${param.name}`);
            } else if (param.name === 'value' && name === 'op_const_u16_sym') {
                // Special case for symbol IDs - print both the ID and the symbol name
                rhs_parts.push(` << ${param.name} << "(" << get_active_global_state()->symbols.get_name_string(${param.name}) << ")"`);
            } else {
                rhs_parts.push(` << ${param.name}`);
            }
        }

        file_lines.push(`            out ${rhs_parts.join('')};`);
        file_lines.push(`            break;`);
        file_lines.push(`        }`);
    }
    file_lines.push(`        default: {}`);
    file_lines.push(`    }`);
    file_lines.push(`}`);
    file_lines.push(``);

    await write_file('src/bytecode/bytecode_encoding.h', file_lines);
}

async function write_file(filename, lines) {
    const outputFilename = Path.join(ProjectRootDir, filename);
    await Fs.writeFile(outputFilename, lines.join('\n'));
    console.log("wrote:", outputFilename);
}

async function main() {
    await write_bytecode_encoding_h();
}

main()
    .catch(err => {
    console.error(err);
    process.exit(1);
});
