// This file was generated by ./ts/generateCpp.ts
// Don't modify this file by hand.
// To change any bytecode operations, update ./ts/bytecodeOps.ts and then run `yarn generate:cpp`

#pragma once

#include "standard_headers.h"
#include "bytecode_helpers.h"
#include "globals/global_state.h"
#include <iostream>

// Const values //

// Indicates an unreachable code path that should never be executed
const u8 OP_UNREACHABLE = 0x0;
// No operation - does nothing
const u8 OP_NOPE = 0x1;
// Halts execution of the current program
const u8 OP_STOP = 0x2;
// Calls function at address, saves frame header in local:0
const u8 OP_CALL = 0x3;
// Returns from current function with value from specified slot
const u8 OP_RETURN = 0x4;
// Calls a host function by symbol, with specified argument count
const u8 OP_CALL_HOST = 0x5;
// Moves value from one slot to another
const u8 OP_MOVE = 0x6;
// Reserves the specified number of slots on the stack
const u8 OP_RESERVE_SLOTS = 0x7;
// Loads a 16-bit signed integer constant into a stack slot
const u8 OP_CONST_I16 = 0x30;
// Loads a 16-bit unsigned integer constant into a stack slot
const u8 OP_CONST_U16 = 0x31;
// Loads a 16-bit symbol ID constant into a stack slot
const u8 OP_CONST_U16_SYM = 0x32;
// Adds two 32-bit integers from the specified stack slots
const u8 OP_I32_ADD = 0x33;
// Subtracts two 32-bit integers from the specified stack slots
const u8 OP_I32_SUB = 0x34;
// Multiplies two 32-bit integers from the specified stack slots
const u8 OP_I32_MULT = 0x35;
// Divides two 32-bit signed integers from the specified stack slots
const u8 OP_I32_DIV_S = 0x36;
// Divides two 32-bit unsigned integers
const u8 OP_I32_DIV_U = 0x37;
// Copies a value from one stack slot to another
const u8 OP_COPY = 0x10;
// Unconditional jump to specified address
const u8 OP_JUMP = 0x40;
// Jump to address if condition slot is true (non-zero)
const u8 OP_JUMP_IF_TRUE = 0x41;
// Jump to address if condition slot is false (zero)
const u8 OP_JUMP_IF_FALSE = 0x42;
// Compare two 32-bit integers for equality
const u8 OP_I32_EQ = 0x38;
// Compare if slot_a < slot_b (signed)
const u8 OP_I32_LT = 0x39;
// Compare if slot_a > slot_b (signed)
const u8 OP_I32_GT = 0x3a;
// Compare if slot_a <= slot_b (signed)
const u8 OP_I32_LE = 0x3b;
// Compare if slot_a >= slot_b (signed)
const u8 OP_I32_GE = 0x3c;
// Compare two 32-bit integers for inequality
const u8 OP_I32_NE = 0x3d;
// Increment 32-bit integer in slot by 1
const u8 OP_I32_INC = 0x3e;
// Represents a compile-time error at this location
const u8 OP_COMPILE_ERROR = 0x60;
// Represents a comment at this location
const u8 OP_COMMENT = 0x61;

// pack functions //

Instruction pack_op_unreachable() {
    Instruction isn = OP_UNREACHABLE << 24;
    return isn;
}

Instruction pack_op_nope() {
    Instruction isn = OP_NOPE << 24;
    return isn;
}

Instruction pack_op_stop() {
    Instruction isn = OP_STOP << 24;
    return isn;
}

Instruction pack_op_call(u16 func_address, u8 stack_size) {
    Instruction isn = OP_CALL << 24;
    isn |= func_address << 8;
    isn |= stack_size << 0;
    return isn;
}

Instruction pack_op_return(u8 return_slot) {
    Instruction isn = OP_RETURN << 24;
    isn |= return_slot << 16;
    return isn;
}

Instruction pack_op_call_host(u8 symbol_slot, u8 argc) {
    Instruction isn = OP_CALL_HOST << 24;
    isn |= symbol_slot << 16;
    isn |= argc << 8;
    return isn;
}

Instruction pack_op_move(u8 from_slot, u8 to_slot) {
    Instruction isn = OP_MOVE << 24;
    isn |= from_slot << 16;
    isn |= to_slot << 8;
    return isn;
}

Instruction pack_op_reserve_slots(u16 count) {
    Instruction isn = OP_RESERVE_SLOTS << 24;
    isn |= count << 8;
    return isn;
}

Instruction pack_op_const_i16(u8 slot, i16 value) {
    Instruction isn = OP_CONST_I16 << 24;
    isn |= slot << 16;
    isn |= value << 0;
    return isn;
}

Instruction pack_op_const_u16(u8 slot, u16 value) {
    Instruction isn = OP_CONST_U16 << 24;
    isn |= slot << 16;
    isn |= value << 0;
    return isn;
}

Instruction pack_op_const_u16_sym(u8 slot, u16 value) {
    Instruction isn = OP_CONST_U16_SYM << 24;
    isn |= slot << 16;
    isn |= value << 0;
    return isn;
}

Instruction pack_op_i32_add(u8 slot_a, u8 slot_b, u8 slot_out) {
    Instruction isn = OP_I32_ADD << 24;
    isn |= slot_a << 16;
    isn |= slot_b << 8;
    isn |= slot_out << 0;
    return isn;
}

Instruction pack_op_i32_sub(u8 slot_a, u8 slot_b, u8 slot_out) {
    Instruction isn = OP_I32_SUB << 24;
    isn |= slot_a << 16;
    isn |= slot_b << 8;
    isn |= slot_out << 0;
    return isn;
}

Instruction pack_op_i32_mult(u8 slot_a, u8 slot_b, u8 slot_out) {
    Instruction isn = OP_I32_MULT << 24;
    isn |= slot_a << 16;
    isn |= slot_b << 8;
    isn |= slot_out << 0;
    return isn;
}

Instruction pack_op_i32_div_s(u8 slot_a, u8 slot_b, u8 slot_out) {
    Instruction isn = OP_I32_DIV_S << 24;
    isn |= slot_a << 16;
    isn |= slot_b << 8;
    isn |= slot_out << 0;
    return isn;
}

Instruction pack_op_i32_div_u() {
    Instruction isn = OP_I32_DIV_U << 24;
    return isn;
}

Instruction pack_op_copy(u8 from_slot, u8 to_slot) {
    Instruction isn = OP_COPY << 24;
    isn |= from_slot << 16;
    isn |= to_slot << 8;
    return isn;
}

Instruction pack_op_jump(u16 address) {
    Instruction isn = OP_JUMP << 24;
    isn |= address << 8;
    return isn;
}

Instruction pack_op_jump_if_true(u8 condition_slot, u16 address) {
    Instruction isn = OP_JUMP_IF_TRUE << 24;
    isn |= condition_slot << 16;
    isn |= address << 0;
    return isn;
}

Instruction pack_op_jump_if_false(u8 condition_slot, u16 address) {
    Instruction isn = OP_JUMP_IF_FALSE << 24;
    isn |= condition_slot << 16;
    isn |= address << 0;
    return isn;
}

Instruction pack_op_i32_eq(u8 slot_a, u8 slot_b, u8 slot_out) {
    Instruction isn = OP_I32_EQ << 24;
    isn |= slot_a << 16;
    isn |= slot_b << 8;
    isn |= slot_out << 0;
    return isn;
}

Instruction pack_op_i32_lt(u8 slot_a, u8 slot_b, u8 slot_out) {
    Instruction isn = OP_I32_LT << 24;
    isn |= slot_a << 16;
    isn |= slot_b << 8;
    isn |= slot_out << 0;
    return isn;
}

Instruction pack_op_i32_gt(u8 slot_a, u8 slot_b, u8 slot_out) {
    Instruction isn = OP_I32_GT << 24;
    isn |= slot_a << 16;
    isn |= slot_b << 8;
    isn |= slot_out << 0;
    return isn;
}

Instruction pack_op_i32_le(u8 slot_a, u8 slot_b, u8 slot_out) {
    Instruction isn = OP_I32_LE << 24;
    isn |= slot_a << 16;
    isn |= slot_b << 8;
    isn |= slot_out << 0;
    return isn;
}

Instruction pack_op_i32_ge(u8 slot_a, u8 slot_b, u8 slot_out) {
    Instruction isn = OP_I32_GE << 24;
    isn |= slot_a << 16;
    isn |= slot_b << 8;
    isn |= slot_out << 0;
    return isn;
}

Instruction pack_op_i32_ne(u8 slot_a, u8 slot_b, u8 slot_out) {
    Instruction isn = OP_I32_NE << 24;
    isn |= slot_a << 16;
    isn |= slot_b << 8;
    isn |= slot_out << 0;
    return isn;
}

Instruction pack_op_i32_inc(u8 slot) {
    Instruction isn = OP_I32_INC << 24;
    isn |= slot << 16;
    return isn;
}

Instruction pack_op_compile_error(u16 error_idx) {
    Instruction isn = OP_COMPILE_ERROR << 24;
    isn |= error_idx << 8;
    return isn;
}

Instruction pack_op_comment(u16 comment_idx) {
    Instruction isn = OP_COMMENT << 24;
    isn |= comment_idx << 8;
    return isn;
}


// unpack functions //

u16 unpack_op_call__func_address(const Instruction ins) {
    return (ins >> 8) & 0xFFFF;
}

u8 unpack_op_call__stack_size(const Instruction ins) {
    return (ins >> 0) & 0xFF;
}

u8 unpack_op_return__return_slot(const Instruction ins) {
    return (ins >> 16) & 0xFF;
}

u8 unpack_op_call_host__symbol_slot(const Instruction ins) {
    return (ins >> 16) & 0xFF;
}

u8 unpack_op_call_host__argc(const Instruction ins) {
    return (ins >> 8) & 0xFF;
}

u8 unpack_op_move__from_slot(const Instruction ins) {
    return (ins >> 16) & 0xFF;
}

u8 unpack_op_move__to_slot(const Instruction ins) {
    return (ins >> 8) & 0xFF;
}

u16 unpack_op_reserve_slots__count(const Instruction ins) {
    return (ins >> 8) & 0xFFFF;
}

u8 unpack_op_const_i16__slot(const Instruction ins) {
    return (ins >> 16) & 0xFF;
}

i16 unpack_op_const_i16__value(const Instruction ins) {
    return (ins >> 0) & 0xFFFF;
}

u8 unpack_op_const_u16__slot(const Instruction ins) {
    return (ins >> 16) & 0xFF;
}

u16 unpack_op_const_u16__value(const Instruction ins) {
    return (ins >> 0) & 0xFFFF;
}

u8 unpack_op_const_u16_sym__slot(const Instruction ins) {
    return (ins >> 16) & 0xFF;
}

u16 unpack_op_const_u16_sym__value(const Instruction ins) {
    return (ins >> 0) & 0xFFFF;
}

u8 unpack_op_i32_add__slot_a(const Instruction ins) {
    return (ins >> 16) & 0xFF;
}

u8 unpack_op_i32_add__slot_b(const Instruction ins) {
    return (ins >> 8) & 0xFF;
}

u8 unpack_op_i32_add__slot_out(const Instruction ins) {
    return (ins >> 0) & 0xFF;
}

u8 unpack_op_i32_sub__slot_a(const Instruction ins) {
    return (ins >> 16) & 0xFF;
}

u8 unpack_op_i32_sub__slot_b(const Instruction ins) {
    return (ins >> 8) & 0xFF;
}

u8 unpack_op_i32_sub__slot_out(const Instruction ins) {
    return (ins >> 0) & 0xFF;
}

u8 unpack_op_i32_mult__slot_a(const Instruction ins) {
    return (ins >> 16) & 0xFF;
}

u8 unpack_op_i32_mult__slot_b(const Instruction ins) {
    return (ins >> 8) & 0xFF;
}

u8 unpack_op_i32_mult__slot_out(const Instruction ins) {
    return (ins >> 0) & 0xFF;
}

u8 unpack_op_i32_div_s__slot_a(const Instruction ins) {
    return (ins >> 16) & 0xFF;
}

u8 unpack_op_i32_div_s__slot_b(const Instruction ins) {
    return (ins >> 8) & 0xFF;
}

u8 unpack_op_i32_div_s__slot_out(const Instruction ins) {
    return (ins >> 0) & 0xFF;
}

u8 unpack_op_copy__from_slot(const Instruction ins) {
    return (ins >> 16) & 0xFF;
}

u8 unpack_op_copy__to_slot(const Instruction ins) {
    return (ins >> 8) & 0xFF;
}

u16 unpack_op_jump__address(const Instruction ins) {
    return (ins >> 8) & 0xFFFF;
}

u8 unpack_op_jump_if_true__condition_slot(const Instruction ins) {
    return (ins >> 16) & 0xFF;
}

u16 unpack_op_jump_if_true__address(const Instruction ins) {
    return (ins >> 0) & 0xFFFF;
}

u8 unpack_op_jump_if_false__condition_slot(const Instruction ins) {
    return (ins >> 16) & 0xFF;
}

u16 unpack_op_jump_if_false__address(const Instruction ins) {
    return (ins >> 0) & 0xFFFF;
}

u8 unpack_op_i32_eq__slot_a(const Instruction ins) {
    return (ins >> 16) & 0xFF;
}

u8 unpack_op_i32_eq__slot_b(const Instruction ins) {
    return (ins >> 8) & 0xFF;
}

u8 unpack_op_i32_eq__slot_out(const Instruction ins) {
    return (ins >> 0) & 0xFF;
}

u8 unpack_op_i32_lt__slot_a(const Instruction ins) {
    return (ins >> 16) & 0xFF;
}

u8 unpack_op_i32_lt__slot_b(const Instruction ins) {
    return (ins >> 8) & 0xFF;
}

u8 unpack_op_i32_lt__slot_out(const Instruction ins) {
    return (ins >> 0) & 0xFF;
}

u8 unpack_op_i32_gt__slot_a(const Instruction ins) {
    return (ins >> 16) & 0xFF;
}

u8 unpack_op_i32_gt__slot_b(const Instruction ins) {
    return (ins >> 8) & 0xFF;
}

u8 unpack_op_i32_gt__slot_out(const Instruction ins) {
    return (ins >> 0) & 0xFF;
}

u8 unpack_op_i32_le__slot_a(const Instruction ins) {
    return (ins >> 16) & 0xFF;
}

u8 unpack_op_i32_le__slot_b(const Instruction ins) {
    return (ins >> 8) & 0xFF;
}

u8 unpack_op_i32_le__slot_out(const Instruction ins) {
    return (ins >> 0) & 0xFF;
}

u8 unpack_op_i32_ge__slot_a(const Instruction ins) {
    return (ins >> 16) & 0xFF;
}

u8 unpack_op_i32_ge__slot_b(const Instruction ins) {
    return (ins >> 8) & 0xFF;
}

u8 unpack_op_i32_ge__slot_out(const Instruction ins) {
    return (ins >> 0) & 0xFF;
}

u8 unpack_op_i32_ne__slot_a(const Instruction ins) {
    return (ins >> 16) & 0xFF;
}

u8 unpack_op_i32_ne__slot_b(const Instruction ins) {
    return (ins >> 8) & 0xFF;
}

u8 unpack_op_i32_ne__slot_out(const Instruction ins) {
    return (ins >> 0) & 0xFF;
}

u8 unpack_op_i32_inc__slot(const Instruction ins) {
    return (ins >> 16) & 0xFF;
}

u16 unpack_op_compile_error__error_idx(const Instruction ins) {
    return (ins >> 8) & 0xFFFF;
}

u16 unpack_op_comment__comment_idx(const Instruction ins) {
    return (ins >> 8) & 0xFFFF;
}

// to_string functions //

const char* bytecode_opcode_to_string(u8 opcode) {
    switch (opcode) {
        case OP_UNREACHABLE: return "op_unreachable";
        case OP_NOPE: return "op_nope";
        case OP_STOP: return "op_stop";
        case OP_CALL: return "op_call";
        case OP_RETURN: return "op_return";
        case OP_CALL_HOST: return "op_call_host";
        case OP_MOVE: return "op_move";
        case OP_RESERVE_SLOTS: return "op_reserve_slots";
        case OP_CONST_I16: return "op_const_i16";
        case OP_CONST_U16: return "op_const_u16";
        case OP_CONST_U16_SYM: return "op_const_u16_sym";
        case OP_I32_ADD: return "op_i32_add";
        case OP_I32_SUB: return "op_i32_sub";
        case OP_I32_MULT: return "op_i32_mult";
        case OP_I32_DIV_S: return "op_i32_div_s";
        case OP_I32_DIV_U: return "op_i32_div_u";
        case OP_COPY: return "op_copy";
        case OP_JUMP: return "op_jump";
        case OP_JUMP_IF_TRUE: return "op_jump_if_true";
        case OP_JUMP_IF_FALSE: return "op_jump_if_false";
        case OP_I32_EQ: return "op_i32_eq";
        case OP_I32_LT: return "op_i32_lt";
        case OP_I32_GT: return "op_i32_gt";
        case OP_I32_LE: return "op_i32_le";
        case OP_I32_GE: return "op_i32_ge";
        case OP_I32_NE: return "op_i32_ne";
        case OP_I32_INC: return "op_i32_inc";
        case OP_COMPILE_ERROR: return "op_compile_error";
        case OP_COMMENT: return "op_comment";
        default: return "(unknown opcode)";
    }
}



u32 bytecode_opcode_get_isn_size(u8 opcode) {
    switch (opcode) {
        case OP_UNREACHABLE: return 1;
        case OP_NOPE: return 1;
        case OP_STOP: return 1;
        case OP_CALL: return 4;
        case OP_RETURN: return 2;
        case OP_CALL_HOST: return 3;
        case OP_MOVE: return 3;
        case OP_RESERVE_SLOTS: return 3;
        case OP_CONST_I16: return 4;
        case OP_CONST_U16: return 4;
        case OP_CONST_U16_SYM: return 4;
        case OP_I32_ADD: return 4;
        case OP_I32_SUB: return 4;
        case OP_I32_MULT: return 4;
        case OP_I32_DIV_S: return 4;
        case OP_I32_DIV_U: return 1;
        case OP_COPY: return 3;
        case OP_JUMP: return 3;
        case OP_JUMP_IF_TRUE: return 4;
        case OP_JUMP_IF_FALSE: return 4;
        case OP_I32_EQ: return 4;
        case OP_I32_LT: return 4;
        case OP_I32_GT: return 4;
        case OP_I32_LE: return 4;
        case OP_I32_GE: return 4;
        case OP_I32_NE: return 4;
        case OP_I32_INC: return 2;
        case OP_COMPILE_ERROR: return 3;
        case OP_COMMENT: return 3;
        default: throw new std::runtime_error("Unknown opcode");
    }
}

void debug_format_instruction(std::ostream& out, Instruction ins) {
    u8 opcode = unpack_opcode(ins);
    out << bytecode_opcode_to_string(opcode);
    switch (opcode) {
        case OP_CALL: {
            u16 func_address = unpack_op_call__func_address(ins);
            u8 stack_size = unpack_op_call__stack_size(ins);
            out  << " func_address:" << func_address << " stack_size:" << (u32)stack_size;
            break;
        }
        case OP_RETURN: {
            u8 return_slot = unpack_op_return__return_slot(ins);
            out  << " return_slot:" << (u32)return_slot;
            break;
        }
        case OP_CALL_HOST: {
            u8 symbol_slot = unpack_op_call_host__symbol_slot(ins);
            u8 argc = unpack_op_call_host__argc(ins);
            out  << " symbol_slot:" << (u32)symbol_slot << " argc:" << (u32)argc;
            break;
        }
        case OP_MOVE: {
            u8 from_slot = unpack_op_move__from_slot(ins);
            u8 to_slot = unpack_op_move__to_slot(ins);
            out  << " from_slot:" << (u32)from_slot << " to_slot:" << (u32)to_slot;
            break;
        }
        case OP_RESERVE_SLOTS: {
            u16 count = unpack_op_reserve_slots__count(ins);
            out  << " count:" << count;
            break;
        }
        case OP_CONST_I16: {
            u8 slot = unpack_op_const_i16__slot(ins);
            i16 value = unpack_op_const_i16__value(ins);
            out  << " slot:" << (u32)slot << " value:" << value;
            break;
        }
        case OP_CONST_U16: {
            u8 slot = unpack_op_const_u16__slot(ins);
            u16 value = unpack_op_const_u16__value(ins);
            out  << " slot:" << (u32)slot << " value:" << value;
            break;
        }
        case OP_CONST_U16_SYM: {
            u8 slot = unpack_op_const_u16_sym__slot(ins);
            u16 value = unpack_op_const_u16_sym__value(ins);
            out  << " slot:" << (u32)slot << " value:" << value << "(" << get_active_global_state()->symbols.get_name_string(value) << ")";
            break;
        }
        case OP_I32_ADD: {
            u8 slot_a = unpack_op_i32_add__slot_a(ins);
            u8 slot_b = unpack_op_i32_add__slot_b(ins);
            u8 slot_out = unpack_op_i32_add__slot_out(ins);
            out  << " slot_a:" << (u32)slot_a << " slot_b:" << (u32)slot_b << " slot_out:" << (u32)slot_out;
            break;
        }
        case OP_I32_SUB: {
            u8 slot_a = unpack_op_i32_sub__slot_a(ins);
            u8 slot_b = unpack_op_i32_sub__slot_b(ins);
            u8 slot_out = unpack_op_i32_sub__slot_out(ins);
            out  << " slot_a:" << (u32)slot_a << " slot_b:" << (u32)slot_b << " slot_out:" << (u32)slot_out;
            break;
        }
        case OP_I32_MULT: {
            u8 slot_a = unpack_op_i32_mult__slot_a(ins);
            u8 slot_b = unpack_op_i32_mult__slot_b(ins);
            u8 slot_out = unpack_op_i32_mult__slot_out(ins);
            out  << " slot_a:" << (u32)slot_a << " slot_b:" << (u32)slot_b << " slot_out:" << (u32)slot_out;
            break;
        }
        case OP_I32_DIV_S: {
            u8 slot_a = unpack_op_i32_div_s__slot_a(ins);
            u8 slot_b = unpack_op_i32_div_s__slot_b(ins);
            u8 slot_out = unpack_op_i32_div_s__slot_out(ins);
            out  << " slot_a:" << (u32)slot_a << " slot_b:" << (u32)slot_b << " slot_out:" << (u32)slot_out;
            break;
        }
        case OP_COPY: {
            u8 from_slot = unpack_op_copy__from_slot(ins);
            u8 to_slot = unpack_op_copy__to_slot(ins);
            out  << " from_slot:" << (u32)from_slot << " to_slot:" << (u32)to_slot;
            break;
        }
        case OP_JUMP: {
            u16 address = unpack_op_jump__address(ins);
            out  << " address:" << address;
            break;
        }
        case OP_JUMP_IF_TRUE: {
            u8 condition_slot = unpack_op_jump_if_true__condition_slot(ins);
            u16 address = unpack_op_jump_if_true__address(ins);
            out  << " condition_slot:" << (u32)condition_slot << " address:" << address;
            break;
        }
        case OP_JUMP_IF_FALSE: {
            u8 condition_slot = unpack_op_jump_if_false__condition_slot(ins);
            u16 address = unpack_op_jump_if_false__address(ins);
            out  << " condition_slot:" << (u32)condition_slot << " address:" << address;
            break;
        }
        case OP_I32_EQ: {
            u8 slot_a = unpack_op_i32_eq__slot_a(ins);
            u8 slot_b = unpack_op_i32_eq__slot_b(ins);
            u8 slot_out = unpack_op_i32_eq__slot_out(ins);
            out  << " slot_a:" << (u32)slot_a << " slot_b:" << (u32)slot_b << " slot_out:" << (u32)slot_out;
            break;
        }
        case OP_I32_LT: {
            u8 slot_a = unpack_op_i32_lt__slot_a(ins);
            u8 slot_b = unpack_op_i32_lt__slot_b(ins);
            u8 slot_out = unpack_op_i32_lt__slot_out(ins);
            out  << " slot_a:" << (u32)slot_a << " slot_b:" << (u32)slot_b << " slot_out:" << (u32)slot_out;
            break;
        }
        case OP_I32_GT: {
            u8 slot_a = unpack_op_i32_gt__slot_a(ins);
            u8 slot_b = unpack_op_i32_gt__slot_b(ins);
            u8 slot_out = unpack_op_i32_gt__slot_out(ins);
            out  << " slot_a:" << (u32)slot_a << " slot_b:" << (u32)slot_b << " slot_out:" << (u32)slot_out;
            break;
        }
        case OP_I32_LE: {
            u8 slot_a = unpack_op_i32_le__slot_a(ins);
            u8 slot_b = unpack_op_i32_le__slot_b(ins);
            u8 slot_out = unpack_op_i32_le__slot_out(ins);
            out  << " slot_a:" << (u32)slot_a << " slot_b:" << (u32)slot_b << " slot_out:" << (u32)slot_out;
            break;
        }
        case OP_I32_GE: {
            u8 slot_a = unpack_op_i32_ge__slot_a(ins);
            u8 slot_b = unpack_op_i32_ge__slot_b(ins);
            u8 slot_out = unpack_op_i32_ge__slot_out(ins);
            out  << " slot_a:" << (u32)slot_a << " slot_b:" << (u32)slot_b << " slot_out:" << (u32)slot_out;
            break;
        }
        case OP_I32_NE: {
            u8 slot_a = unpack_op_i32_ne__slot_a(ins);
            u8 slot_b = unpack_op_i32_ne__slot_b(ins);
            u8 slot_out = unpack_op_i32_ne__slot_out(ins);
            out  << " slot_a:" << (u32)slot_a << " slot_b:" << (u32)slot_b << " slot_out:" << (u32)slot_out;
            break;
        }
        case OP_I32_INC: {
            u8 slot = unpack_op_i32_inc__slot(ins);
            out  << " slot:" << (u32)slot;
            break;
        }
        case OP_COMPILE_ERROR: {
            u16 error_idx = unpack_op_compile_error__error_idx(ins);
            out  << " error_idx:" << error_idx;
            break;
        }
        case OP_COMMENT: {
            u16 comment_idx = unpack_op_comment__comment_idx(ins);
            out  << " comment_idx:" << comment_idx;
            break;
        }
        default: {}
    }
}
